tsoding/bm

- .github/workflows/ci.yml
just copied from ebisp. also builds the examples, but does not run them (since some of them might need limits, eg. `fib`)
> Add github actions CI for linux and macos

- Makefile
- README.md
- examples/pi.basm
- src/bm.h
Had some fun implementing a (slow approximation of) pi example in basm. In the course of doing that I ran into some missing instructions in the source translation function. 
The pi example makes use of a loop based on a counter to stop calculation.
The result after running it is:
```
$ ./bme -i examples/pi.bm
Stack:
u64: 4614256658053244912, i64: 4614256658053244912, f64: 3.141593, ptr: 0x400921fbadbea7f0
```
> Implement pi example

- src/bm.h
This PR displays specific error messages instead of the generic `ERROR: Could not open file ....`.
> Distinguish the 4 different causes for I/O errors.

- .github/workflows/ci.yml
- .gitignore
- build_msvc.bat
- src/bm.h
- src/debasm.c
Close #20 
Fixed MSVC errors:
* Not all switch cases return a value
* Same as in #16 (Differing definitions of `int64_t`)
* Expected constant expression for `char cstr[sv.count + 1];`
> (#20) Add MSVC build for CI

- build_msvc.bat
- src/basm.c
- src/bm.h
Close #12 
~~Also batch file now gets list of examples directly from Makefile, so we don't need to maintain two lists.~~
All `*.basm` files from `examples` folder now builds automatically.
> (#12) Add line number to source translating error

- src/bm.h
Hi, I am not sure about implementation here but at least error from native call should be propagated somehow.
> Do not swallow error from native call

- examples/hello.basm
- src/bm.h
Ran into issue while implementing #62 where I could not add a comment after a string literal when doing a %bind.
This change will chop of all comments for any line
Close #72
> (#72) Comments after string literals raises an error 

- README.md
- tools/basm.vim
As described by the comment block in the file, it requires the next line in the `.vimrc`:
``` vim
autocmd BufRead,BufNewFile *.basm set filetype=basm
```
and the `basm.vim` file should be placed in the `.vim/syntax/` folder
> Introduce basm-mode for vim

- examples/rot13.basm
Fixed the bug where I was referring to addresses instead of using the `secret` label.
This bug now became visible thanks to the buffer that was introduced in natives.hasm for the dump_u64 implementation.
Also, I used character literals now that they've been implemented
> Fix rot13 example

- tools/basm-mode.el
I was going crazy looking at Emacs not colouring `jmp_if` correctly in the files, so I swapped its position with `jmp` in the keywords list.
> Update basm-mode.el to make jmp_if have the right colouring

- .github/workflows/ci.yml
- build_msvc.bat
- src/basm2nasm.c
`basm2nasm` now prints comments with labels from basm source. That way it's easier to debug x86_64 executable.
~~When I emulate `chars.bm` I get ERR_STACK_UNDERFLOW. So I replaced `ret` with `halt`.~~ Fixed in e68e388
To make scripts more consistent, `build_msvc.bat` rebuilds examples even without argument.
~~Also it can now automatically find and launch MSVC console tools.~~
> Add comments to asm with labels from basm

- src/bdb.c
Parsing commands used to fail when the started with whitespace
characters.
Fixes #163 
Please let me know if you have any issues with this PR.
> (#163) Fix parsing bug in BDB

- src/bdb.c
No associated issue.
We used to print the address of a particular label. Now we print the
label itself.
Please let me know if you have any issues with the changes.
> BDB : Implement printing labels for call, jmp and jmp_if

- src/bdb.c
- src/bdb.h
This changes the names of the following commands:
+ Stack dump can be printed with 'p'
+ Single stepping instructions can be done with 's'
+ Stepping over instructions can be achieved with 'n'
Please let me know if you have any issues with the changes.
> BDB : Implement stepping over call instructions

- .gitignore
- nobuild.c
- src/library/bm.h
- src/library/native_loader.c
- wrappers/bm_hello.c
- wrappers/bm_sdl.c
OwO
requires `lib/SDL2.lib` and `include/SDL2/` under `bm/vendor/sdl2`
requires `SDL2.dll` and `libbm_sdl.dll` to run the SDL example
> Dynamic loading of objects on Windows #268

- src/library/basm.c
- src/library/basm.h
- src/library/statement.c
- src/library/statement.h
Close #319 
On stream you [mentioned](https://www.twitch.tv/videos/994203851?t=00h38m04s) `Bind_` suffix in some of those types. So I also added this:
```
// TODO: Remove redundant prefix `bind` from *_Statement types
```
> (#319) Add `_Statement` suffix to all of the Statement kind types

- src/library/basm.c
- src/library/basm.h
- src/library/statement.c
- src/library/statement.h
Close #327 
Also removed `Bind` from `dump_statement` function output for `Const` statement:
<details>
<summary>git diff</summary>
```diff
-        fprintf(stream, "%*sBind Const:\n", level * 2, "");
+        fprintf(stream, "%*sConst:\n", level * 2, "");
```
</details
> (#327) Remove `bind` prefix from statement types and all derived names

- src/toolchain/basm2nasm.c
Call `basm_translate_root_source_file` instead of `basm_translate_source_file` so it doesn't crash because of scopes
All `FIXME`'s are now straight up asserts
Also now it can handle include paths, instructions for comparing integers (`gei`/`geu`, `gti`/`gtu`, `lei`/`leu`, `lti`/`ltu`, `nei`/`neu` and `equ`)  and `multu`
HACKERMANS
> Make basm2nasm a bit better

- nobuild.c
- src/library/basm.c
All basm instructions are now implemented in nasm HYPERS
Tests can be now compiled to native executables via `./nobuild cases nasm`
When `nobuild` is compiled not for linux it will fail with assert on attempt to compile tests via nasm.
`./nobuild test nasm` will also fail with assert, because there is no mechanism to capture and check output of tests build with nasm yet
> Make basm's nasm output format even better than before

- nobuild.c
- src/library/basm.c
- src/library/basm.h
- src/toolchain/basm.c
Since the code it generates works only Linux x86_64. So I decided to
emphasize that with the name.
> Rename `basm -f nasm` to `basm -f nasm-linux-x86-64`

- src/library/basm.c
- src/library/basm.h
- src/toolchain/basm.c
Adapts syscall-IDs for FreeBSD so we don't have to use `brandelf'.
I renamed `basm_save_to_file_as_nasm_linux_x86_64' to
`basm_save_to_file_as_nasm_sysv_x86_64' since effectively we're using
the SystemV AMD64 calling convention here. The only thing that
differs are the syscall ids, which is the additional argument, that
the function now takes.
Also, I'm not quite sure about the type name `Syscall_Target' so if
anyone has got a better name: go ahead!
> Add FreeBSD target for Native Codegen via NASM

- src/library/bm.c
- src/library/gas_arm64.c
Together with #380 and #381, this makes bm/basm work on SPARC and Solaris (10).
> Fix unaligned memory access in emulator

- nobuild.c
You can specify more than one tool as well, eg. `./nobuild tools bme bang`
> Add `./nobuild tools <tool>...` to selectively build tools

- src/library/gas_arm64.c
As noted in the commit message of 07eef8b .
I removed the jump table because it seemed like a hack anyways. Now we
use the proper call/return mechanisms of arm slightly modified to use
the bm stack instead of the "C stack" (which doesn't really exist
since we don't depend on libc).
Maybe this can be done to the amd64 assembly generator as well.
Spoiler: Performance slightly increased:
``` console
[nico@henricus ~/src/bm]$ build/toolchain/basm -t gas-freebsd-arm64 -I lib test/cases/pi.basm
[nico@henricus ~/src/bm]$ cc -c -g -o pi.o pi.S
[nico@henricus ~/src/bm]$ ld -o pi pi.o
[nico@henricus ~/src/bm]$ time ./pi
3.1415933203
real   0.273605
user   0.273777
sys    0.000000
[nico@henricus ~/src/bm]$ time ./pi
3.1415933203
real   0.273515
user   0.273590
sys    0.000243
[nico@henricus …
```
> arm64 : Remove awkward jump table

- src/library/nasm_sysv_x86_64.c
- Clean out rax before doing the comparison to sweep out the upper
bits as only the lower 16 bits get set (Thanks to abridgewater)
- Fix cleaning xmm0 (Thanks to kolumbetko)
> (#373) Fix pi = 4 in amd64 assembly-gen

- nobuild.c
Was completely broken. Now builds on both amd64 and arm64 FreeBSD.
No change of #348 :
``` console
...
[INFO] CMD: ld build/test/cases/read-write.o -o build/test/cases/read-write.elf64
[INFO] CMD: build/toolchain/basm -I ./lib/ -t gas-freebsd-arm64 test/cases/rot13.basm -o build/test/cases/rot13.S
[INFO] CMD: cc -c -g build/test/cases/rot13.S -o build/test/cases/rot13.o
[INFO] CMD: ld build/test/cases/rot13.o -o build/test/cases/rot13.elf64
Assertion failed: (0 && "TODO(#348): implement some mechanism to test native executables"), function test_command, file nobuild.c, line 402.
[2] + Abort trap - core dumped    ./nobuild test asm
[nico@henricus ~/src/bm]$
```
> Fix broken nobuild on FreeBSD 

- src/toolchain/debasm.c
> (#406) Make the output of `debasm` compilable with `basm` again

- src/library/gas_arm64.c
- src/library/nasm_sysv_x86_64.c
The id of the `write` native is not fixed to 0. It depends on the order of the definition in the original BASM file. The actual native should be determined by its name.
cc @zhiayang @herrhotzenplotz @kolumb sorry that I did not catch that during the reviews. Pinging you just to let you know about this. Also, please let me know if my changes introduced any bugs
> Handle native instructions properly in code generators

- bdb/src/bdb.c
- bdb/src/bdb.h
See notes in commit message.
As bdb seems a little bit broken and no issues exist/are linked for
the actual issues, I removed a couple of things that are outdated
(e.g. the symtab) and turned them into a TODO (snitch-ing required).
This makes bdb at least usable and not fail at startup, trying to find
the symbol table. Also, I stole some code from bme to load the native
write implementation, such that the virtual machine throws an error
when stepping into native write instruction.
Might fix #100 (not sure whether we can remove it)
> bdb : Fix startup failures

- bang/src/bang.c
- bang/src/bang_compiler.c
- bang/src/bang_compiler.h
> (#458) Implement the compilation of the local variables

- bang/src/bang_compiler.c
> (#456) Implement variable assignment

- bang/src/bang_compiler.c
- bang/src/bang_compiler.h
> (#454) Implement local variable reading

- bdb/src/bdb.c
Makes it a bit more pleasing to the eye. And it improves the UX.
```console
[nico@hades ~/src/bm/bdb]$ bin/bdb ../pi.bm
BDB - The birtual machine debugger.
Type 'h' and enter for a quick help
TODO(<redacted unrelated issue>): BDB does not load symbols from a symbol table
(bdb) b 104
INFO : Breakpoint set at 104
(bdb) r
Hit breakpoint at 104 label ''
(bdb) x 0 128
00000000: 33 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00000070: 00 00 00 00 00 00 …
```
> bdb : Print a better memory dump

- bang/examples/gol.bang
- bang/examples/rule110.bang
- bang/src/bang.c
- bang/src/bang_compiler.c
- bang/src/bang_compiler.h
> (#455) Implement ptr() for local vars and fix the semantics of the stack frames

- bang/src/bang_compiler.c
> (#470) Treat the stack frame var as the var of type ptr

- bang/src/bang_compiler.c
> (#457) Variable shadowing warning

- bang/nobuild.c
- bang/src/bang.c
- bang/src/bang_compiler.c
- bang/src/bang_compiler.h
- bang/src/bang_diag.c
- bang/src/bang_diag.h
- bang/src/bang_lexer.h
> (#481) Treat variable shadowing warning as error if requested
