tsoding/bm

Makefile
examples/fib.basm
src/basm.c
src/bm.h
src/bme.c

(#2) Implement labels for Assembly

---

.gitignore
Makefile
src/nan.c

(#4) Add prototype implementation of NaN boxing

---

Makefile
examples/lerp.basm
src/bm.h

(#3) Introduce call/ret semantics

---

Makefile
examples/123f.basm
examples/123i.basm
examples/alloc.basm
examples/e.basm
examples/fib.basm
examples/lerp.basm
examples/pi.basm
src/bm.h
src/bme.c

(#5) Introduce native function mechanism

---

Makefile

This is still not POSIX, but at least it runs with both of those make flavours.

Makefile: Adapt to make it both Berkeley and GNU Make compatible

---

README.md
examples/fib.basm

(#32) Improve fib.basm example

---

examples/lerp.basm
src/bm.h

(#34) Make lerp more interesting

---

examples/bits.basm
examples/gray.basm
src/bm.h

(#11) Implement bitwise instructions

---

build.sh
examples/memory.basm
examples/natives.hasm
src/bm.h
src/bme.c

(#48) Introduce memory into the machine definition

---

examples/alloc.basm
examples/bits.basm
examples/fib.basm
examples/gray.basm
examples/memory.basm
examples/natives.hasm
src/bm.h

(#63) labels -> bindings

---

README.md
examples/hello.basm
examples/natives.hasm
src/basm.c
src/bm.h
src/bme.c

(#60) Introduce support for string literals

---

src/bm.h

(#70) Change magic

---

examples/rot13.basm
src/bm.h
src/bme.c

I implemented ROT13. Showcasing function calls and the new memory read/write mechanism.
In the course of doing that I implemented GEI and MODI instructions. 
Close #62

(#62) rot13 example that read/writes data from/to the bm memory

---

.gitignore
build.sh
build_msvc.bat
src/basm.c
src/bdb.c
src/bdb.h
src/bm.h

This adds basic functionality for a dbx-style debugger (#61)
As always, I left off a few TODOs in the code.
What does not work yet is:
+ Examine memory
+ Native function calls (they are not initialized and therefore cause all programs that use them to fault in the debugger)
+ User input is a bit janky. That neads a bit of a polish in order to improve the UX
Please tell me, if you want me to squash some commits.

(#61) dbx-style step debugger

---

examples/bits.basm
examples/e.basm
examples/fib.basm
examples/gray.basm
examples/lerp.basm
examples/memory.basm
examples/rot13.basm
src/bm.h
tools/basm-mode.el

(#38) Complete comparison instruction set

---

examples/cast.basm
src/bm.h
tools/basm-mode.el

(#39) Introduce instructions i2f, u2f, f2i, f2u

---

src/bdb.c
src/bm.h
src/bme.c

(#84) Load native functions in bdb

---

build_msvc.bat
src/bdb.c
src/bdb.h
src/bm.h

(#82) Build bdb on windows

---

.github/workflows/ci.yml

(#103) Build x86_64 examples on Linux

---

src/bdb.c

(#115) Make bdb exit on ^D

---

examples/chars.basm
src/bm.h
tools/basm-mode.el
tools/basm.vim

(#120) Add support for character literals

---

src/bdb.c

(#85) Introduce basic way to inspect the memory in bdb

---

build-x86_64.sh
examples/123i.basm
examples/bits.basm
examples/cast.basm
examples/fib.basm
examples/gray.basm
examples/natives.hasm
examples/print_u64_test.basm
src/basm2nasm.c
tools/x86_64.gdb

(#105) Introduce dump_u64 function and deprecate print_u64 native function

---

examples/natives.hasm
src/basm2nasm.c
tools/x86_64.gdb

(#105) make dump_u64 compilable with basm2nasm

---

src/basm.c
src/bdb.c
src/bm.h

(#52) Location reporting on second pass

---

src/bm.h

(#124) Report original entry point location on entry point resetting

---

examples/123f.basm
examples/cast.basm
examples/e.basm
examples/lerp.basm
examples/natives.hasm
examples/pi.basm
src/basm2nasm.c
src/bm.h

(#130) Deprecate print_f64 in favor of dump_f64

---

src/bm.h

(#51) Report binding redefinition location

---

src/basm2nasm.c
tools/x86_64.gdb

(#140) Implement some instructions for x86_64 translator

---

src/bdb.c
src/bdb.h

This fixes #94 
If you have any issues with this implementation, please let me know :-)

(#94) BDB : Implement repeating the previous command on hitting ENTER

---

examples/natives.hasm
src/basm2nasm.c
src/bm.h
src/bmr.c

(#152) Remove dead natives from the list of standard natives

---

src/basm.c
src/bdb.c
src/bdb.h

See #158 
Also adds a TODO.
Please let me know if you have any issues with this PR.

(#158) Implement distinguishing between different kinds of bindings in BDB 

---

src/bdb.c
src/bm.h
src/bmr.c

(#143) make %include report location if the file does not exist

---

src/bdb.c
src/bdb.h

Deprecates the `i` command, as you can use the `w` command instead to print information about the current location in the program.
Please let me know if you have any issues with the changes.

BDB : Introduce `w` command in favour of the `i` command

---

nobuild.c
src/basm.c
src/basm2nasm.c
src/bdb.c
src/bm.h
src/bmr.c

(#154) Integrate region-based memory allocator as the Arena

---

src/basm.c
src/bdb.c
src/bm.h

(#77) Make string literals introduce second binding for their size

---

src/bm.h

(#172) Introduce Expr AST for compile time evaluation

---

src/bm.h

(#177) add expression support for bindings

---

src/bdb.c
src/bdb.h
src/bm.h

It is a bit more difficult than anticipated.
The issue is the breakpoints. (See my notes in the code)

(#88) Reset the debugger and reload program

---

.github/workflows/ci.yml
.github/workflows/formatting.yml
.gitignore
CONTRIBUTING.md
README.md
nobuild.c
src/basm2nasm.c
src/bdb.c
src/bdb.h
src/bm.h

- Refactor subcommand system in nobuild.c
- Introduce `nobuild fmt` subcommand
- Check formatting on CI

Check formatting on CI

---

examples/hello.basm
src/bm.h

(#182) Introduce len() translation function

---

nobuild.c
nobuild.h

(#193) Fix nobuild warnings on clang and gcc

---

src/library/expr.c
src/library/sv.h

(#199) make parse_primary_from_tokens support parens

---

src/library/expr.c

(#202) make expressions left associative by default

---

src/toolchain/bdb.c

(#189) Fix ^D error reporting in bdb

---

nobuild.h

seg fault without it for me

---

examples/direct-memory-access.basm
nobuild.c
src/library/basm.c
test/examples/direct-memory-access.expected.out

(#214) force evaluate bindings after the first pass of translation

---

src/library/basm.c
src/library/basm.h

(#234) Introduce AST assert translation

---

src/library/basm.c
src/library/basm.h
src/toolchain/basm.c

(#233) Introduce AST translation for %include directive

---

src/library/basm.c
src/library/basm.h
src/library/expr.c
src/library/expr.h
src/library/statement.c
src/library/statement.h
src/library/tokenizer.c

(#210) Introduce %error directive

---

src/library/statement.c

(#235) set statement location during the parsing

---

src/library/basm.c
src/library/basm.h
src/library/statement.c
src/library/statement.h

(#210) Introduce %if construction into the AST

---

examples/direct-memory-access.basm.ignored
src/library/basm.c
src/library/basm.h
src/library/expr.c
src/library/expr.h
src/library/statement.h
src/library/tokenizer.c
src/library/tokenizer.h

(#210) Finally implement working %if block

---

src/library/basm.c
src/library/basm.h
src/library/fl.h
src/library/sv.h

(#245) Implement better error message for the if-label paradox

---

examples/stdlib/natives.hasm
nobuild.c
src/library/basm.c
src/library/basm.h
src/library/statement.c
src/library/statement.h
src/toolchain/basm.c
src/toolchain/basm2nasm.c

(#211) Introduce scopes

---

src/library/basm.c
src/library/basm.h
src/toolchain/basm.c

(#251)  Make deferred entry point evaluation a per scope process

---

src/library/basm.c
src/library/statement.c
src/library/statement.h

(#246) Introduce %else branch for %if

---

examples/bits.basm
examples/compile-time-exprs.basm
examples/fib.basm
examples/gray.basm
examples/hello.basm
examples/pi.basm
examples/prime.basm
examples/rot13.basm
examples/stdlib/natives.hasm
src/library/expr.c
src/library/statement.c
src/library/tokenizer.c
src/library/tokenizer.h

(#227) make = part of the %const and %native syntax

---

examples/multichar-literal.basm
examples/stdlib/natives.hasm
src/library/basm.c
src/library/bm.h
src/library/expr.c
src/library/expr.h
test/examples/multichar-literal.expected.out

(#258) Implement multichar literals

---

src/library/basm.c
src/library/linizer.c
src/library/linizer.h
src/library/statement.c
src/library/statement.h
src/toolchain/basm2dot.c

(#255) Implement %elif support for %if construction

---

examples/compile-time-fib.basm.ignored
src/library/basm.c
src/library/expr.c
src/library/expr.h
src/library/statement.c
src/library/statement.h
src/library/tokenizer.c
src/library/tokenizer.h

(#212) Introduce Fundef to AST

---

lib/sdl.hasm
lib/std.hasm
src/library/basm.c
src/library/basm.h
src/library/bm.c
src/library/bm.h
src/library/statement.c
src/library/statement.h
src/toolchain/bdb.c
src/toolchain/bme.c
src/toolchain/bmr.c

(#266) merge %external and %native mechanisms together

---

nobuild.c
src/library/path.c

This fixes #217
All tests are passing locally.

(#217) Fix build on FreeBSD

---

src/library/expr.c
src/library/expr.h
src/library/statement.c
test/cases/hello.basm
test/outputs/hello.expected.out

(#66) Introduce escaping to the string literals

---

examples/sdl.basm
wrappers/bm_sdl.c

(#280) Unhardcode title parameter in the SDL_CreateWindow function

---

lib/std.hasm
src/library/basm.c
src/library/statement.c

(#67) Some improvements while working on #67

---

src/library/arena.c

fix visual bug on Windows

---

src/library/basm.c
src/library/expr.c
src/library/linizer.c
src/library/statement.c
src/library/statement.h
src/library/tokenizer.c
src/library/tokenizer.h

(#304) Extend AST to support macro definitions and macro calls

---

src/library/basm.c
src/library/basm.h
src/library/statement.h

(#310) Implement macrodef translation

---

src/library/basm.c
src/library/basm.h
src/library/expr.c
src/library/expr.h
src/library/statement.c
src/library/statement.h

(#318) Implement basm_translate_macro_call()

---

src/library/expr.c

(#324) Implement dump_fundef_args_as_dot_edges()

---

src/library/statement.c

(#311) Try to make "unknown directive" error message less confusing

---

src/library/basm.c
src/library/basm.h
src/library/types.c
src/library/types.h
src/toolchain/bdb.c
src/toolchain/bdb.h

(#305) ReplaceBinding_Kind with Type

---

src/library/basm.c
src/library/basm.h

(#305) Implement simple type check during expr evaluation

---

examples/sdl.basm
src/library/basm.c
src/library/bm.c
src/library/bm.h
src/library/types.c
src/library/types.h

(#342) Implement the type casting

---

src/library/basm.c
src/library/basm.h

(#326) Add `_statement` suffix to all statement translating functions

---

nobuild.c
src/library/basm.c
src/library/bm.c
src/library/types.c

(#340) Implement static type checking for deferred operands

---

nobuild.c
src/library/basm.c
src/library/types.c
src/library/types.h

(#341) Make compile type binary operations work with any numbers

---

src/library/basm.c
src/library/bm.c
src/library/types.c
src/library/types.h

(#356) Introduce Bool type

---

src/library/verifier.c
src/library/verifier.h

(#359) Report the location type mismatching args of instructions

---

docs/builtin-natives.md
lib/std.hasm
src/library/bm.c
src/library/bm.h
src/toolchain/bme.c
src/toolchain/bmr.c

(#351) Introduce built-in external native function

---

lib/std.hasm

(#127) Better way of allocating memory for std printing functions

---

nobuild.h

It was still segfaulting on arm64 ...
See:
- https://github.com/tsoding/nobuild/pull/24
- https://github.com/tsoding/nobuild/pull/25

Update nobuild dependency

---

tools/basm-mode.el

I was missing my line-numbers.

Make basm-mode derive from prog-mode

---

src/library/gas_arm64.c

Sorry for the PR spam :|
Fixes #396
See comments of dbb6014

(#396) Fix wrong behavior of f2u in arm64 code-gen

---

src/library/bm.c
src/library/bm.h
src/library/expr.c
src/library/sv.c
src/library/sv.h
src/toolchain/debasm.c

(#403) Make debasm generate natives and memory

---

src/library/bang_compiler.c
src/library/bang_compiler.h
src/library/bang_parser.c
src/library/bang_parser.h
src/toolchain/bang.c

(#410) Properly handle entry point in Bang compilation

---

src/library/bang_compiler.c
src/library/bang_compiler.h
src/library/bang_parser.c
src/library/bang_parser.h
src/toolchain/bang.c

(#415) Implement additional procedures for Bang

---

src/library/basm.c
src/library/basm.h
src/library/nasm_sysv_x86_64.c

Label names

---

examples/hello.bang
src/library/bang_compiler.c
src/library/bang_parser.h
src/library/nasm_sysv_x86_64.c

(#421) Add type `bool`

---

examples/ptr.bang
src/library/bang_compiler.c
src/library/bang_compiler.h
src/library/bang_parser.c
src/library/bang_parser.h
src/library/nasm_sysv_x86_64.c
src/toolchain/bang.c

(#428) Add initial pointers support

---

src/library/bang_compiler.c
src/library/bang_parser.c
src/library/bang_parser.h

(#438) Implement precedence for binary operators

---

src/library/sv.c

(#434) fix sv_parse_hex

---

examples/gol.bang
src/library/bang_lexer.c
src/library/bang_lexer.h
src/library/bang_parser.c

(#445) Introduce a separate token for the equality operation

---

test/cases/rot13.basm

(#81) Remove string length hack from rot13 example

---

bang/README.md
bang/examples/rule110.bang
bang/src/bang.c
basm/src/compiler.c
basm/src/compiler.h

(#462) Implement run subcommand for bang compiler
